# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: menu.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

# Menubar functions

ID_OPEN = 10000
ID_CLOSE = 10001
ID_EXIT = 10002
ID_FILE = 10003

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item2 = wx.MenuItem( item1, ID_OPEN, "Apri", "" )
    item2.SetBitmap( MyBitmapsFunc( 0 ) )
    item1.AppendItem( item2 )
    item3 = wx.MenuItem( item1, ID_CLOSE, "Chiudi", "" )
    item3.SetBitmap( MyBitmapsFunc( 1 ) )
    item1.AppendItem( item3 )
    item4 = wx.MenuItem( item1, ID_EXIT, "Esci", "" )
    item4.SetBitmap( MyBitmapsFunc( 2 ) )
    item1.AppendItem( item4 )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

ID_TBOPEN = 10004
ID_TOOL = 10005

def MyToolBarFunc( parent ):
    parent.SetMargins( [10,10] )
    
    parent.AddLabelTool( ID_TBOPEN, "uno", MyBitmapsFunc( 0 ), wx.NullBitmap, wx.ITEM_NORMAL, "descrizione uno ...... ", "messaggio uno" )
    parent.AddLabelTool( ID_TOOL, "descrizione due ..............", MyBitmapsFunc( 1 ), wx.NullBitmap, wx.ITEM_NORMAL, "" )
    parent.AddLabelTool( ID_TOOL, "descrizione tre ...........", MyBitmapsFunc( 2 ), wx.NullBitmap, wx.ITEM_NORMAL, "" )
    parent.AddLabelTool( ID_TOOL, "asdada", MyBitmapsFunc( 3 ), wx.NullBitmap, wx.ITEM_NORMAL, "asdasasd", "asdasdas" )
    
    parent.Realize()

# Bitmap functions


def MyBitmapsFunc( index ):
    if index == 0:
        return wx.Image( "menu_wdr/MyBitmapsFunc_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 1:
        return wx.Image( "menu_wdr/MyBitmapsFunc_1.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 2:
        return wx.Image( "menu_wdr/MyBitmapsFunc_2.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 3:
        return wx.Image( "menu_wdr/MyBitmapsFunc_3.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
