# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: menu.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

ID_TEXT = 10000
ID_TEXTCTRL = 10001
ID_RADIOBUTTON = 10002

def RiepilogoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 5, 0, 0 )
    
    item1.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item2 = wx.StaticText( parent, ID_TEXT, "Anno riferimento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Mese o trimestre di riferimento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item1.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 2 )

    item1.AddGrowableCol( 4 )

    item0.Add( item1, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.FlexGridSizer( 0, 5, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "TIPO COMUNICAZIONE", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.RadioButton( parent, ID_RADIOBUTTON, "Dati Aggregati.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.RadioButton( parent, ID_RADIOBUTTON, "Dati Analitici", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6.AddGrowableCol( 0 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "text", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "text", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item14 = wx.StaticText( parent, ID_TEXT, "text", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "text", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "text", wx.DefaultPosition, wx.DefaultSize, 0 )
    item0.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item0.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANEL = 10003

def QuadroGenericoFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item1 = wx.Panel( parent, ID_PANEL, wx.DefaultPosition, [200,160], 0 )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_LINE = 10004

def TitolareFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item1.AddGrowableCol( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "DATI IDENTIF.DEL SOGGETTO  CUI ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetForegroundColour( wx.RED )
    item3.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticText( parent, ID_TEXT, "Partita IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.StaticText( parent, ID_TEXT, "Codice Fiscale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Codice Attività", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "SI RIFERISCE LA COMUNICAZIONE", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetForegroundColour( wx.RED )
    item3.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item3.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item3.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item3.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.AddGrowableCol( 1 )

    item3.AddGrowableCol( 2 )

    item3.AddGrowableCol( 3 )

    item0.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item13 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [900,-1], wx.LI_HORIZONTAL )
    item12.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item12.AddGrowableCol( 0 )

    item0.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14 = wx.FlexGridSizer( 0, 5, 0, 0 )
    
    item15 = wx.StaticText( parent, ID_TEXT, "DATI ANAGRAFICI ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetForegroundColour( wx.RED )
    item14.Add( item15, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item16 = wx.StaticText( parent, ID_TEXT, "Cognome", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item16, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item17 = wx.StaticText( parent, ID_TEXT, "Nome", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item17, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item18 = wx.StaticText( parent, ID_TEXT, "Sesso", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item14.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item19 = wx.StaticText( parent, ID_TEXT, "PERSONE FISICHE", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetForegroundColour( wx.RED )
    item14.Add( item19, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 0 )

    item20 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item20, 0, wx.GROW|wx.ALL, 5 )

    item21 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item22 = wx.RadioButton( parent, ID_RADIOBUTTON, "Maschio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item22, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item23 = wx.RadioButton( parent, ID_RADIOBUTTON, "Femmina", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item23, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( [ 20, 20 ] , 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Data Nascita", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "Comune", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26 = wx.StaticText( parent, ID_TEXT, "Provincia", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item27 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item27, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item28 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item29 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item29, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.AddGrowableCol( 1 )

    item14.AddGrowableCol( 2 )

    item0.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item30 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item31 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item30.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item30.AddGrowableCol( 0 )

    item0.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_NOTEBOOK = 10005
ID_BUTSAVE = 10006

def DataEntryFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.Notebook( parent, ID_NOTEBOOK, wx.DefaultPosition, [800,380], 0 )
    item2 = item3
    
    item4 = wx.Panel( item3, -1 )
    item3.AddPage( item4, "Titolare" )

    item5 = wx.Panel( item3, -1 )
    item3.AddPage( item5, "Quadro FA" )

    item6 = wx.Panel( item3, -1 )
    item3.AddPage( item6, "Quadro SA" )

    item7 = wx.Panel( item3, -1 )
    item3.AddPage( item7, "Quadro BL" )

    item8 = wx.Panel( item3, -1 )
    item3.AddPage( item8, "Riepilogo" )

    item1.Add( item2, 0, wx.GROW|wx.ALL, 5 )

    item9 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item9.Add( [ 20, 20 ] , 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.Button( parent, ID_BUTSAVE, "Conferma", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "butsave" )
    item9.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item9.AddGrowableCol( 0 )

    item1.Add( item9, 0, wx.GROW|wx.ALL, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_IMPORTFILE = 10007
ID_QUIT = 10008
ID_IMPORT = 10009

def ImportFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Comunicazione da Importare", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = FullPathFileEntryCtrl( parent, ID_IMPORTFILE, "", wx.DefaultPosition, [500,-1], 0 )
    item3.SetName( "Import_file" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [500,-1], wx.LI_HORIZONTAL )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.AddGrowableCol( 0 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item6.Add( [ 20, 20 ] , 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.Button( parent, ID_QUIT, "Abbandona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "btnImportQuit" )
    item6.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.Button( parent, ID_IMPORT, "Importa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "btnImportFile" )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6.AddGrowableCol( 0 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_VIEWTEXT = 10010
ID_BTNNOTEPAD = 10011
ID_VIEW = 10012

def VisualizzaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Comunicazione da Importare", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = FullPathFileEntryCtrl( parent, ID_IMPORTFILE, "", wx.DefaultPosition, [500,-1], 0 )
    item3.SetName( "Import_file" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [900,-1], wx.LI_HORIZONTAL )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.AddGrowableCol( 0 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item7 = wx.TextCtrl( parent, ID_VIEWTEXT, "", wx.DefaultPosition, [80,500], wx.TE_MULTILINE )
    item7.SetFont( wx.Font( 12, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item7.SetName( "viewcomunicazione" )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item6.AddGrowableCol( 0 )

    item6.AddGrowableRow( 0 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item9 = wx.Button( parent, ID_BTNNOTEPAD, "Visualizza in Windows", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8.Add( [ 20, 20 ] , 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item10 = wx.Button( parent, ID_QUIT, "Abbandona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "btnImportQuit" )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.Button( parent, ID_VIEW, "Visualizza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "btnImportFile" )
    item8.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8.AddGrowableCol( 1 )

    item0.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 2 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

ID_OPEN = 10013
ID_CLOSE = 10014
ID_EXIT = 10015
ID_FILE = 10016

def MyMenuBarFunc():
    item0 = wx.MenuBar()
    
    item1 = wx.Menu()
    item2 = wx.MenuItem( item1, ID_OPEN, "Apri", "" )
    item2.SetBitmap( MyBitmapsFunc( 0 ) )
    item1.AppendItem( item2 )
    item3 = wx.MenuItem( item1, ID_CLOSE, "Chiudi", "" )
    item3.SetBitmap( MyBitmapsFunc( 1 ) )
    item1.AppendItem( item3 )
    item4 = wx.MenuItem( item1, ID_EXIT, "Esci", "" )
    item4.SetBitmap( MyBitmapsFunc( 2 ) )
    item1.AppendItem( item4 )
    item0.Append( item1, "File" )
    
    return item0

# Toolbar functions

ID_TBOPEN = 10017
ID_TOOL = 10018

def MyToolBarFunc( parent ):
    parent.SetMargins( [10,10] )
    
    parent.AddLabelTool( ID_TBOPEN, "uno", MyBitmapsFunc( 0 ), wx.NullBitmap, wx.ITEM_NORMAL, "descrizione uno ...... ", "messaggio uno" )
    parent.AddLabelTool( ID_TOOL, "descrizione due ..............", MyBitmapsFunc( 1 ), wx.NullBitmap, wx.ITEM_NORMAL, "" )
    parent.AddLabelTool( ID_TOOL, "descrizione tre ...........", MyBitmapsFunc( 2 ), wx.NullBitmap, wx.ITEM_NORMAL, "" )
    parent.AddLabelTool( ID_TOOL, "asdada", MyBitmapsFunc( 3 ), wx.NullBitmap, wx.ITEM_NORMAL, "asdasasd", "asdasdas" )
    
    parent.Realize()

# Bitmap functions


def MyBitmapsFunc( index ):
    if index == 0:
        return wx.Image( "menu_wdr/MyBitmapsFunc_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 1:
        return wx.Image( "menu_wdr/MyBitmapsFunc_1.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 2:
        return wx.Image( "menu_wdr/MyBitmapsFunc_2.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    if index == 3:
        return wx.Image( "menu_wdr/MyBitmapsFunc_3.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
